"""Tests for the GROMACS .xvg parser and its nm→Å relabelling."""

import pytest

from gromd_analysis.xvg import _nm_to_angstrom, parse_xvg

XVG = """\
# generated by gmx rms
# some other comment
@    title "RMSD"
@    xaxis  label "Time (ps)"
@    yaxis  label "RMSD (nm)"
@ s0 legend "Backbone"
@ s1 legend "Backbone after lsq fit"
    0.0000000    0.0000000    0.0000000
   10.0000000    0.1234000    0.1000000

   20.0000000    0.2500000    0.2000000
"""


@pytest.fixture
def xvg_file(tmp_path):
    p = tmp_path / "rmsd.xvg"
    p.write_text(XVG)
    return p


def test_parses_grace_directives(xvg_file):
    d = parse_xvg(xvg_file)
    assert d.title == "RMSD"
    assert d.xlabel == "Time (ps)"
    assert d.ylabel == "RMSD (nm)"
    assert d.legends == {0: "Backbone", 1: "Backbone after lsq fit"}


def test_columns_are_transposed_and_skip_comments_and_blanks(xvg_file):
    d = parse_xvg(xvg_file)
    assert len(d.columns) == 3
    assert d.columns[0] == [0.0, 10.0, 20.0]
    assert d.columns[1] == [0.0, 0.1234, 0.25]
    assert d.columns[2] == [0.0, 0.1, 0.2]


def test_ragged_rows_are_rejected(tmp_path):
    p = tmp_path / "ragged.xvg"
    p.write_text("0.0 1.0 2.0\n1.0 1.0\n")
    with pytest.raises(AssertionError):
        parse_xvg(p)


def test_no_data_rows_exits(tmp_path):
    p = tmp_path / "empty.xvg"
    p.write_text('@    title "nothing"\n')
    with pytest.raises(SystemExit):
        parse_xvg(p)


# ── the units gotcha: gmx writes nm, structural work reads Å ─────────────────

def test_nm_label_is_relabelled_and_flagged_for_scaling():
    assert _nm_to_angstrom("RMSD (nm)") == ("RMSD (Å)", True)


def test_label_without_nm_is_untouched():
    assert _nm_to_angstrom("Time (ps)") == ("Time (ps)", False)


def test_nm_matches_only_as_a_whole_word():
    # "nmol" must not be mistaken for a nanometre unit.
    label, scale = _nm_to_angstrom("Amount (nmol)")
    assert (label, scale) == ("Amount (nmol)", False)
